# Generated by Django 5.1 on 2024-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_productos', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_añadido', models.DateField()),
            ],
        ),
    ]
